config/routes.rb
Rails.application.routes.draw do
  resources :transfers
  resources :grade_fixeds
  resources :grades
  resources :fixeds
  resources :etc_lists
  resources :access_types
  resources :calendars
  resources :gradelists
  resources :city_names
  
  resources :orders
  # resources :orders, only: [:index] do
  #   collection do
  #     get :search
  #   end
  # end
  
  resources :users
  # resources :others
  # resources :daily_allowances
  # resources :accommodations
  # resources :transport_costs
  # resources :reports
  resources :reports do
    resources :others
    resources :daily_costs
    # resources :daily_allowances
    # resources :additionals
    # resources :accommodations
    resources :transport_costs
    # resources :moving_times
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/access_type.rb
class AccessType < ApplicationRecord
end

app/models/additional.rb
class Additional < ApplicationRecord
  belongs_to :report
end

app/models/calendar.rb
class Calendar < ApplicationRecord
end

app/models/city_name.rb
class CityName < ApplicationRecord
    # belongs_to :accommodation
end

app/models/daily_cost.rb
class DailyCost < ApplicationRecord
  belongs_to :report
end

app/models/etc_list.rb
class EtcList < ApplicationRecord
end

app/models/fixed.rb
class Fixed < ApplicationRecord
end

app/models/grade.rb
class Grade < ApplicationRecord
end

app/models/grade_fixed.rb
class GradeFixed < ApplicationRecord
  belongs_to :fixed
  belongs_to :grade
end

app/models/gradelist.rb
class Gradelist < ApplicationRecord
end

app/models/moving_path.rb
class MovingPath < ApplicationRecord
  belongs_to :moving_time
end

app/models/moving_route.rb
class MovingRoute < ApplicationRecord
  belongs_to :moving_time
end

app/models/moving_time.rb
class MovingTime < ApplicationRecord
    belongs_to :report
    
    has_many :moving_routes
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  
  has_many :reports
end

app/models/other.rb
class Other < ApplicationRecord
  belongs_to :report
end

app/models/path.rb
class Path < ApplicationRecord
  belongs_to :moving_time
end

app/models/report.rb
class Report < ApplicationRecord
    belongs_to :order
    
    # has_many :accommodations
    has_many :transport_costs
    # has_many :daily_allowances
    # has_many :additionals
    has_many :others
    # has_many :moving_times
    has_many :daily_costs
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :user
  belongs_to :grade
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/access_types_controller.rb
class AccessTypesController < ApplicationController
  before_action :set_access_type, only: [:show, :edit, :update, :destroy]

  # GET /access_types
  # GET /access_types.json
  def index
    @access_types = AccessType.all
  end

  # GET /access_types/1
  # GET /access_types/1.json
  def show
  end

  # GET /access_types/new
  def new
    @access_type = AccessType.new
  end

  # GET /access_types/1/edit
  def edit
  end

  # POST /access_types
  # POST /access_types.json
  def create
    @access_type = AccessType.new(access_type_params)

    respond_to do |format|
      if @access_type.save
        format.html { redirect_to @access_type, notice: 'Access type was successfully created.' }
        format.json { render :show, status: :created, location: @access_type }
      else
        format.html { render :new }
        format.json { render json: @access_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /access_types/1
  # PATCH/PUT /access_types/1.json
  def update
    respond_to do |format|
      if @access_type.update(access_type_params)
        format.html { redirect_to @access_type, notice: 'Access type was successfully updated.' }
        format.json { render :show, status: :ok, location: @access_type }
      else
        format.html { render :edit }
        format.json { render json: @access_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /access_types/1
  # DELETE /access_types/1.json
  def destroy
    @access_type.destroy
    respond_to do |format|
      format.html { redirect_to access_types_url, notice: 'Access type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_access_type
      @access_type = AccessType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def access_type_params
      params.require(:access_type).permit(:moving_type)
    end
end

app/helpers/access_types_helper.rb
module AccessTypesHelper
end

app/helpers/paths_helper.rb
module PathsHelper
end

app/views/access_types/_form.html.erb
<%= form_with(model: access_type, local: true) do |form| %>
  <% if access_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(access_type.errors.count, "error") %> prohibited this access_type from being saved:</h2>

      <ul>
      <% access_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :moving_type %>
    <%= form.text_field :moving_type, id: :access_type_moving_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/access_types/edit.html.erb
<h1>Editing Access Type</h1>

<%= render 'form', access_type: @access_type %>

<%= link_to 'Show', @access_type %> |
<%= link_to 'Back', access_types_path %>

app/views/access_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Access Types</h1>

<table>
  <thead>
    <tr>
      <th>Moving type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @access_types.each do |access_type| %>
      <tr>
        <td><%= access_type.moving_type %></td>
        <td><%= link_to 'Show', access_type %></td>
        <td><%= link_to 'Edit', edit_access_type_path(access_type) %></td>
        <td><%= link_to 'Destroy', access_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Access Type', new_access_type_path %>

app/views/access_types/new.html.erb
<h1>New Access Type</h1>

<%= render 'form', access_type: @access_type %>

<%= link_to 'Back', access_types_path %>

app/views/access_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Moving type:</strong>
  <%= @access_type.moving_type %>
</p>

<%= link_to 'Edit', edit_access_type_path(@access_type) %> |
<%= link_to 'Back', access_types_path %>