config/routes.rb
Rails.application.routes.draw do
  resources :transfers
  resources :grade_fixeds
  resources :grades
  resources :fixeds
  resources :etc_lists
  resources :access_types
  resources :calendars
  resources :gradelists
  resources :city_names
  
  resources :orders
  # resources :orders, only: [:index] do
  #   collection do
  #     get :search
  #   end
  # end
  
  resources :users
  # resources :others
  # resources :daily_allowances
  # resources :accommodations
  # resources :transport_costs
  # resources :reports
  resources :reports do
    resources :others
    resources :daily_costs
    # resources :daily_allowances
    # resources :additionals
    # resources :accommodations
    resources :transport_costs
    # resources :moving_times
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/access_type.rb
class AccessType < ApplicationRecord
end

app/models/additional.rb
class Additional < ApplicationRecord
  belongs_to :report
end

app/models/calendar.rb
class Calendar < ApplicationRecord
end

app/models/city_name.rb
class CityName < ApplicationRecord
    # belongs_to :accommodation
end

app/models/daily_cost.rb
class DailyCost < ApplicationRecord
  belongs_to :report
end

app/models/etc_list.rb
class EtcList < ApplicationRecord
end

app/models/fixed.rb
class Fixed < ApplicationRecord
end

app/models/grade.rb
class Grade < ApplicationRecord
end

app/models/grade_fixed.rb
class GradeFixed < ApplicationRecord
  belongs_to :fixed
  belongs_to :grade
end

app/models/gradelist.rb
class Gradelist < ApplicationRecord
end

app/models/moving_path.rb
class MovingPath < ApplicationRecord
  belongs_to :moving_time
end

app/models/moving_route.rb
class MovingRoute < ApplicationRecord
  belongs_to :moving_time
end

app/models/moving_time.rb
class MovingTime < ApplicationRecord
    belongs_to :report
    
    has_many :moving_routes
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  
  has_many :reports
end

app/models/other.rb
class Other < ApplicationRecord
  belongs_to :report
end

app/models/path.rb
class Path < ApplicationRecord
  belongs_to :moving_time
end

app/models/report.rb
class Report < ApplicationRecord
    belongs_to :order
    
    # has_many :accommodations
    has_many :transport_costs
    # has_many :daily_allowances
    # has_many :additionals
    has_many :others
    # has_many :moving_times
    has_many :daily_costs
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :user
  belongs_to :grade
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :set_transfer, only: [:show, :edit, :update, :destroy]

  # GET /transfers
  # GET /transfers.json
  def index
    @transfers = Transfer.all
  end

  # GET /transfers/1
  # GET /transfers/1.json
  def show
  end

  # GET /transfers/new
  def new
    @transfer = Transfer.new
  end

  # GET /transfers/1/edit
  def edit
  end

  # POST /transfers
  # POST /transfers.json
  def create
    @transfer = Transfer.new(transfer_params)

    respond_to do |format|
      if @transfer.save
        format.html { redirect_to @transfer, notice: 'Transfer was successfully created.' }
        format.json { render :show, status: :created, location: @transfer }
      else
        format.html { render :new }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transfers/1
  # PATCH/PUT /transfers/1.json
  def update
    respond_to do |format|
      if @transfer.update(transfer_params)
        format.html { redirect_to @transfer, notice: 'Transfer was successfully updated.' }
        format.json { render :show, status: :ok, location: @transfer }
      else
        format.html { render :edit }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transfers/1
  # DELETE /transfers/1.json
  def destroy
    @transfer.destroy
    respond_to do |format|
      format.html { redirect_to transfers_url, notice: 'Transfer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transfer
      @transfer = Transfer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transfer_params
      params.require(:transfer).permit(:user_id, :grade_id, :transfer_type, :transfer_date)
    end
end

app/helpers/paths_helper.rb
module PathsHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/transfers/_form.html.erb
<%= form_with(model: transfer, local: true) do |form| %>
  <% if transfer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transfer.errors.count, "error") %> prohibited this transfer from being saved:</h2>

      <ul>
      <% transfer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :transfer_user_id %>
  </div>

  <div class="field">
    <%= form.label :grade_id %>
    <%= form.text_field :grade_id, id: :transfer_grade_id %>
  </div>

  <div class="field">
    <%= form.label :transfer_type %>
    <%= form.text_field :transfer_type, id: :transfer_transfer_type %>
  </div>

  <div class="field">
    <%= form.label :transfer_date %>
    <%= form.date_select :transfer_date, id: :transfer_transfer_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transfers/edit.html.erb
<h1>Editing Transfer</h1>

<%= render 'form', transfer: @transfer %>

<%= link_to 'Show', @transfer %> |
<%= link_to 'Back', transfers_path %>

app/views/transfers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transfers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Grade</th>
      <th>Transfer type</th>
      <th>Transfer date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transfers.each do |transfer| %>
      <tr>
        <td><%= transfer.user %></td>
        <td><%= transfer.grade %></td>
        <td><%= transfer.transfer_type %></td>
        <td><%= transfer.transfer_date %></td>
        <td><%= link_to 'Show', transfer %></td>
        <td><%= link_to 'Edit', edit_transfer_path(transfer) %></td>
        <td><%= link_to 'Destroy', transfer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transfer', new_transfer_path %>

app/views/transfers/new.html.erb
<h1>New Transfer</h1>

<%= render 'form', transfer: @transfer %>

<%= link_to 'Back', transfers_path %>

app/views/transfers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @transfer.user %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @transfer.grade %>
</p>

<p>
  <strong>Transfer type:</strong>
  <%= @transfer.transfer_type %>
</p>

<p>
  <strong>Transfer date:</strong>
  <%= @transfer.transfer_date %>
</p>

<%= link_to 'Edit', edit_transfer_path(@transfer) %> |
<%= link_to 'Back', transfers_path %>