config/routes.rb
Rails.application.routes.draw do
  resources :transfers
  resources :grade_fixeds
  resources :grades
  resources :fixeds
  resources :etc_lists
  resources :access_types
  resources :calendars
  resources :gradelists
  resources :city_names
  
  resources :orders
  # resources :orders, only: [:index] do
  #   collection do
  #     get :search
  #   end
  # end
  
  resources :users
  # resources :others
  # resources :daily_allowances
  # resources :accommodations
  # resources :transport_costs
  # resources :reports
  resources :reports do
    resources :others
    resources :daily_costs
    # resources :daily_allowances
    # resources :additionals
    # resources :accommodations
    resources :transport_costs
    # resources :moving_times
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/access_type.rb
class AccessType < ApplicationRecord
end

app/models/additional.rb
class Additional < ApplicationRecord
  belongs_to :report
end

app/models/calendar.rb
class Calendar < ApplicationRecord
end

app/models/city_name.rb
class CityName < ApplicationRecord
    # belongs_to :accommodation
end

app/models/daily_cost.rb
class DailyCost < ApplicationRecord
  belongs_to :report
end

app/models/etc_list.rb
class EtcList < ApplicationRecord
end

app/models/fixed.rb
class Fixed < ApplicationRecord
end

app/models/grade.rb
class Grade < ApplicationRecord
end

app/models/grade_fixed.rb
class GradeFixed < ApplicationRecord
  belongs_to :fixed
  belongs_to :grade
end

app/models/gradelist.rb
class Gradelist < ApplicationRecord
end

app/models/moving_path.rb
class MovingPath < ApplicationRecord
  belongs_to :moving_time
end

app/models/moving_route.rb
class MovingRoute < ApplicationRecord
  belongs_to :moving_time
end

app/models/moving_time.rb
class MovingTime < ApplicationRecord
    belongs_to :report
    
    has_many :moving_routes
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  
  has_many :reports
end

app/models/other.rb
class Other < ApplicationRecord
  belongs_to :report
end

app/models/path.rb
class Path < ApplicationRecord
  belongs_to :moving_time
end

app/models/report.rb
class Report < ApplicationRecord
    belongs_to :order
    
    # has_many :accommodations
    has_many :transport_costs
    # has_many :daily_allowances
    # has_many :additionals
    has_many :others
    # has_many :moving_times
    has_many :daily_costs
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :user
  belongs_to :grade
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]



  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
    # logger.debug @reports.inspect
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    
  # @daily_allowances_total =  @report.daily_allowances.sum(:fixed) + @report.daily_allowances.sum(:fixed_over) + @report.daily_allowances.sum(:moving_allowance)
  # @accomodation_total = @report.accommodations.sum(:accommodation) + @report.accommodations.sum(:add_money)
  # @transport_cost_total =  @report.transport_costs.sum(:transport_cost)
  # @other_total = @report.others.sum(:other_money)
  # # @etc = @report.transport_costs.where(exclusion_type: 'etc')
  # # @etc_total = @etc.sum(:transport_cost)
  # # @airticket = @report.transport_costs.where(exclusion_type: '航空券')
  # # @airticket_total = @airticket.sum(:transport_cost)
  # @adjusted_amount = @daily_allowances_total + @accomodation_total + @transport_cost_total + @other_total
  
  # if @adjusted_amount > @report.tmp_money + @etc_total + @airticket_total
  #     @add_money = @adjusted_amount - @report.tmp_money - @etc_total - @airticket_total
  #   else
  #     @return_money = @report.tmp_money + @etc_total + @airticket_total - @adjusted_amount
  # end
  
  # 出発時刻がdatetime型の為、一度日付毎に集計
  # @move_total = MovingTime.where("holiday_type = '休日'").group("DATE(dept_date)").sum(:moving_time).to_a
  
  # if @move_total.values{1} < 240
  #   @move_allowance = 2000
  # elseif @move_total.values < 360
  #   @move_allowance = 4000
  # else
  #   @move_allowance = 6000
  # end
  
  logger.debug @move_total.inspect
    
  @reports = Report.all
  @order = Order.find(@report.order_id)
  @user = User.find(@order.user_id)
  # @user_n = Transfer.where(:user_id => 1).first
  # @user_g = @user_n.grade_id
  # @grade_list = GradeFixed.where(:grade_id => @user_g)
  # @grade_value = @grade_list.where(:chanege_date < "2019-01-21").last
  # # @grade_n = Grade_fixed.
  # logger.debug @grade_value.inspect
  
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:order_id, :purpose, :bussiness_trip, :address, :distance, :apply_date, :create_date, :adjusted_amount, :tmp_money, :return_money, :add_money)
    end
end

app/helpers/paths_helper.rb
module PathsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :order_id %>
    <%= form.number_field :order_id, id: :report_order_id %>
  </div>
  
  <div class="field">
    <%= form.label :purpose %>
    <%= form.text_field :purpose, id: :report_purpose %>
  </div>
  
  <div class="field">
    <%= form.label :bussiness_trip %>
    <%= form.text_field :bussiness_trip, id: :report_bussiness_trip %>
  </div>
  
  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :report_address %>
  </div>
  
  <div class="field">
    <%= form.label :distance %>
    <%= form.number_field :distance, id: :report_distance %>
  </div>

  <div class="field">
    <%= form.label :apply_date %>
    <%= form.date_select :apply_date, id: :report_apply_date %>
  </div>

  <div class="field">
    <%= form.label :create_date %>
    <%= form.date_select :create_date, id: :report_create_date %>
  </div>

  <div class="field">
    <%= form.label :adjusted_amount %>
    <%= form.number_field :adjusted_amount, id: :report_adjusted_amount %>
  </div>

  <div class="field">
    <%= form.label :tmp_money %>
    <%= form.number_field :tmp_money, id: :report_tmp_money %>
  </div>

  <div class="field">
    <%= form.label :return_money %>
    <%= form.number_field :return_money, id: :report_return_money %>
  </div>

  <div class="field">
    <%= form.label :add_money %>
    <%= form.number_field :add_money, id: :report_add_money %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>

<table>
  <thead>
    <tr>
      <th>Apply date</th>
      <th>Create date</th>
      <th>Adjusted amount</th>
      <th>Tmp money</th>
      <th>Return money</th>
      <th>Add money</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.apply_date %></td>
        <td><%= report.create_date %></td>
        <td><%= report.adjusted_amount %></td>
        <td><%= report.tmp_money %></td>
        <td><%= report.return_money %></td>
        <td><%= report.add_money %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <tr><%= debug report.inspect %></tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', reports_path %>

app/views/reports/new.js.erb
$("#cost-modal").html("<%= escape_javascript(render 'form', report: @report, daily_cost: @daily_cost) %>")
$("#cost-modal").modal("show")

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-md-6">
      
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>氏名</th>
          </tr>
        </thead>
        <tbody>
          <td><di><%= @user.emp_name%></di></td>
        </tbody>
      </table>
    
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>UDNO</th>
            <th>SKNO</th>
            <th>客先</th>
          </tr>
        </thead>
        <tbody>
          <td><di><%= @order.udno %></di></td>
          <td><di><%= @order.skno %></di></td>
          <td><di><%= @order.customer %></di></td>
        </tbody>
      </table>
      
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>出張先</th>
            <th>出張先住所</th>
            <th>直線距離</th>
            <th>出張用件</th>
          </tr>
        </thead>
        <tbody>
          <td><di><%= @report.bussiness_trip %></di></td>
          <td><di><%= @report.address %></di></td>
          <td><di><%= @report.distance %>Km</di></td>
          <td><di><%= @report.purpose %></di></td>
        </tbody>
      </table>
      
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div id="sortable">
        
        <h3 id="transport_cost">交通費</h3>
        <table class="table">
            <thead>
              <tr>
                <th>移動日</th>
                <th>起点名</th>
                <th>終着点</th>
                <!--<th>移動経路</th>-->
                <th>移動方法</th>
                <th>ETC</th>
                <th>交通費</th>
                <th></th>
                <th></th>
              </tr>
            </thead>
                    <% @report.transport_costs.each do |t| %>
            <tbody>
                <tr>
                  <td><div><%= t.move_date %></div></td>
                  <td><div><%= t.dept %></div></td>
                  <td><div><%= t.dest %></div></td>
                  <!--<td><div><%= t.root %></div></td>-->
                  <td><div><%= t.access %></div></td>
                  <!--<td><div>%= t.exclusion_type %></div></td>-->
                  <!--<td><div>%= t.drive_type %></div></td>-->
                  <td><div><%= t.etc %></div></td>
                  <td align="right"><div><%= number_with_delimiter(t.transport_cost) %></div></td>
                  <td><%= link_to 'Edit', edit_report_transport_cost_path(t.report_id,t.id) %> <%= link_to 'Destroy', report_transport_cost_path(t.report_id,t.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
                <tr>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td><b>計</b></td>
                  <td align="right"><div><%= number_with_delimiter(@report.transport_costs.sum(:transport_cost)) %></div></td>
                </tr>
            </tbody>
        </table>
        <div class="pull-right">
          <h4>交通費　<%= number_with_delimiter(@transport_cost_total) %><h4>
        </div>
        
        <%= link_to '交通費追加', new_report_transport_cost_url(@report.id), remote: true,class: "btn btn-lg btn-primary" %> 
        
        <div class="modal fade" id="transport_cost-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"></div>
        
      <div id="allowance"><h3>日当</h3></div>
        <table class="table">
            <thead>
              <tr>
                <th>日付</th>
                <th>金額</th>
                <th></th>
              </tr>
            </thead>
            
            <tbody>
              <% @report.daily_costs.where(expenses_type: '日当').each do |d| %>
                <tr>
                  <td><div><%= d.daily_date %></div></td>
                  <td><div><%= d.daily_cost %></div></td>
                  <td><%= link_to 'Edit', edit_report_daily_cost_path(d.report_id,d.id) %> <%= link_to 'Destroy', report_daily_cost_path(d.report_id,d.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
              <tr>
                <td></td>
                <td><b>計</b></td>
                <td align="right"><div><%= number_with_delimiter(@report.daily_costs.where(expenses_type: '日当').sum(:daily_cost)) %></div></td>
              </tr>
            </tbody>
        </table>
        <div class="pull-right">
          <h4>経費 　<%= number_with_delimiter(@other_total) %></h4>
        </div>
        
        <%= link_to '日当追加', new_report_daily_cost_url(@report.id) ,class: "btn btn-lg btn-primary"%> 
        
        <div id="allowance"><h3>日当割増</h3></div>
        <table class="table">
            <thead>
              <tr>
                <th>日付</th>
                <th>出発時刻</th>
                <th>到着時刻</th>
                <th>金額</th>
                <th></th>
              </tr>
            </thead>
            
            <tbody>
              <% @report.daily_costs.where(expenses_type: '日当割増').each do |d| %>
                <tr>
                  <td><div><%= d.daily_date %></div></td>
                  <td><div><%= d.dept_time.strftime('%H:%M:%S') %></div></td>
                  <td><div><%= d.dest_ime.strftime('%H:%M:%S') %></div></td>
                  <td><div><%= d.daily_cost %></div></td>
                  <td><%= link_to 'Edit', edit_report_daily_cost_path(d.report_id,d.id) %> <%= link_to 'Destroy', report_daily_cost_path(d.report_id,d.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
              <tr>
                <td></td>
                <td><b>計</b></td>
                <td align="right"><div><%= number_with_delimiter(@report.daily_costs.where(expenses_type: '日当割増').sum(:daily_cost)) %></div></td>
              </tr>
            </tbody>
        </table>
        <div class="pull-right">
          <h4>経費 　<%= number_with_delimiter(@other_total) %></h4>
        </div>
        
        <%= link_to '日当割増追加', new_report_daily_cost_url(@report.id),class: "btn btn-lg btn-primary" %> 
        
        <div id="allowance"><h3>宿泊費</h3></div>
        <table class="table">
            <thead>
              <tr>
                <th>日付</th>
                <th>出発時刻</th>
                <th>到着時刻</th>
                <th>都市名</th>
                <th>金額</th>
                <th></th>
              </tr>
            </thead>
            
            <tbody>
              <% @report.daily_costs.where(expenses_type: '宿泊費').each do |d| %>
                <tr>
                  <td><div><%= d.daily_date %></div></td>
                  <td><div><%= d.dept_time.strftime('%H:%M:%S') %></div></td>
                  <td><div><%= d.dest_ime.strftime('%H:%M:%S') %></div></td>
                  <td><div><%= d.city_name %></div></td>
                  <td><div><%= d.daily_cost %></div></td>
                  <td><%= link_to 'Edit', edit_report_daily_cost_path(d.report_id,d.id) %> <%= link_to 'Destroy', report_daily_cost_path(d.report_id,d.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
              <tr>
                <td></td>
                <td><b>計</b></td>
                <td align="right"><div><%= number_with_delimiter(@report.daily_costs.where(expenses_type: '宿泊費').sum(:daily_cost)) %></div></td>
              </tr>
            </tbody>
        </table>
        <div class="pull-right">
          <h4>経費 　<%= number_with_delimiter(@other_total) %></h4>
        </div>
        
        <%= link_to '宿泊費追加', new_report_daily_cost_url(@report.id),class: "btn btn-lg btn-primary" %>
        
      <div id="allowance"><h3>移動手当</h3></div>
        <table class="table">
            <thead>
              <tr>
                <th>日付</th>
                <th>経路</th>
                <th>移動時間</th>
                <th>金額</th>
                <th></th>
              </tr>
            </thead>
            
            <tbody>
              <% @report.daily_costs.where(expenses_type: '移動手当').each do |d| %>
                <tr>
                  <td><div><%= d.daily_date %></div></td>
                  <td><div><%= d.course %></div></td>
                  <td><div><%= d.travel_hour %></div></td>
                  <td><div><%= d.daily_cost %></div></td>
                  <td><%= link_to 'Edit', edit_report_daily_cost_path(d.report_id,d.id) %> <%= link_to 'Destroy', report_daily_cost_path(d.report_id,d.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
              <tr>
                <td></td>
                <td><b>計</b></td>
                <td align="right"><div><%= number_with_delimiter(@report.daily_costs.where(expenses_type: '移動手当').sum(:daily_cost)) %></div></td>
              </tr>
            </tbody>
        </table>
        <div class="pull-right">
          <h4>経費 　<%= number_with_delimiter(@other_total) %></h4>
        </div>
        
        <%= link_to '移動手当追加', new_report_daily_cost_url(@report.id), remote: true, class: "btn btn-lg btn-primary" %> 
        
        <div id="cost-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
        
        <div id="other"><h3>雑費</h3></div>
        <table class="table">
            <thead>
              <tr>
                <th>支払日</th>
                <th>内容</th>
                <th>金額</th>
                <th></th>
              </tr>
            </thead>
            
            <tbody>
              <% @report.others.each do |o| %>
                <tr>
                  <td><div><%= o.payment_date %></div></td>
                  <td><div><%= o.content %></div></td>
                  <td align="right"><div><%= number_with_delimiter(o.other_money) %></div></td>
                  <td><%= link_to 'Edit', edit_report_other_path(o.report_id,o.id) %> <%= link_to 'Destroy', report_other_path(o.report_id,o.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
              <tr>
                <td></td>
                <td><b>計</b></td>
                <td align="right"><div><%= number_with_delimiter(@report.others.sum(:other_money)) %></div></td>
              </tr>
            </tbody>
        </table>
        <div class="pull-right">
          <h4>雑費　<%= number_with_delimiter(@other_total) %></h4>
        </div>
        
        <%= link_to '雑費追加', new_report_other_url(@report.id),class: "btn btn-lg btn-primary" %> 
        
      </div>
    </div>
    
    <div class="col-md-6">
    
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>精算額</th>
            <th>仮払金</th>
            <th>ETC</th>
            <th>航空券</th>
          </tr>
        </thead>
        <tbody>
          <td><di><%= number_with_delimiter(@adjusted_amount) %></di></td>
          <td><di><%= number_with_delimiter(@report.tmp_money) %></di></td>
          <td><di><%= number_with_delimiter(@etc_total) %></di></td>
          <td><di><%= number_with_delimiter(@airticket_total) %></di></td>
        </tbody>
      </table>
      
          <table class="table table-bordered">
        <thead>
          <tr>
            <th>返戻金</th>
            <th>追加支給</th>
          </tr>
        </thead>
        <tbody>
          <td><di><%= number_with_delimiter(@return_money) %></di></td>
          <td><di><%= number_with_delimiter(@add_money) %></di></td>
        </tbody>
      </table>
      
    </div>
    <div class="col-md-6"></div>
  
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="pull-right">
      <%= link_to "帳票",{ :format => "pdf" }, :class => 'btn btn-primary' %>
      <%= link_to 'Edit', edit_report_path(@report) %> 
      <%= link_to 'Back', reports_path %>
    </div>
  </div>
</div>