config/routes.rb
Rails.application.routes.draw do
  resources :transfers
  resources :grade_fixeds
  resources :grades
  resources :fixeds
  resources :etc_lists
  resources :access_types
  resources :calendars
  resources :gradelists
  resources :city_names
  
  resources :orders
  # resources :orders, only: [:index] do
  #   collection do
  #     get :search
  #   end
  # end
  
  resources :users
  # resources :others
  # resources :daily_allowances
  # resources :accommodations
  # resources :transport_costs
  # resources :reports
  resources :reports do
    resources :others
    resources :daily_costs
    # resources :daily_allowances
    # resources :additionals
    # resources :accommodations
    resources :transport_costs
    # resources :moving_times
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/access_type.rb
class AccessType < ApplicationRecord
end

app/models/additional.rb
class Additional < ApplicationRecord
  belongs_to :report
end

app/models/calendar.rb
class Calendar < ApplicationRecord
end

app/models/city_name.rb
class CityName < ApplicationRecord
    # belongs_to :accommodation
end

app/models/daily_cost.rb
class DailyCost < ApplicationRecord
  belongs_to :report
end

app/models/etc_list.rb
class EtcList < ApplicationRecord
end

app/models/fixed.rb
class Fixed < ApplicationRecord
end

app/models/grade.rb
class Grade < ApplicationRecord
end

app/models/grade_fixed.rb
class GradeFixed < ApplicationRecord
  belongs_to :fixed
  belongs_to :grade
end

app/models/gradelist.rb
class Gradelist < ApplicationRecord
end

app/models/moving_path.rb
class MovingPath < ApplicationRecord
  belongs_to :moving_time
end

app/models/moving_route.rb
class MovingRoute < ApplicationRecord
  belongs_to :moving_time
end

app/models/moving_time.rb
class MovingTime < ApplicationRecord
    belongs_to :report
    
    has_many :moving_routes
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  
  has_many :reports
end

app/models/other.rb
class Other < ApplicationRecord
  belongs_to :report
end

app/models/path.rb
class Path < ApplicationRecord
  belongs_to :moving_time
end

app/models/report.rb
class Report < ApplicationRecord
    belongs_to :order
    
    # has_many :accommodations
    has_many :transport_costs
    # has_many :daily_allowances
    # has_many :additionals
    has_many :others
    # has_many :moving_times
    has_many :daily_costs
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :user
  belongs_to :grade
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/etc_lists_controller.rb
class EtcListsController < ApplicationController
  before_action :set_etc_list, only: [:show, :edit, :update, :destroy]

  # GET /etc_lists
  # GET /etc_lists.json
  def index
    @etc_lists = EtcList.all
  end

  # GET /etc_lists/1
  # GET /etc_lists/1.json
  def show
  end

  # GET /etc_lists/new
  def new
    @etc_list = EtcList.new
  end

  # GET /etc_lists/1/edit
  def edit
  end

  # POST /etc_lists
  # POST /etc_lists.json
  def create
    @etc_list = EtcList.new(etc_list_params)

    respond_to do |format|
      if @etc_list.save
        format.html { redirect_to @etc_list, notice: 'Etc list was successfully created.' }
        format.json { render :show, status: :created, location: @etc_list }
      else
        format.html { render :new }
        format.json { render json: @etc_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /etc_lists/1
  # PATCH/PUT /etc_lists/1.json
  def update
    respond_to do |format|
      if @etc_list.update(etc_list_params)
        format.html { redirect_to @etc_list, notice: 'Etc list was successfully updated.' }
        format.json { render :show, status: :ok, location: @etc_list }
      else
        format.html { render :edit }
        format.json { render json: @etc_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /etc_lists/1
  # DELETE /etc_lists/1.json
  def destroy
    @etc_list.destroy
    respond_to do |format|
      format.html { redirect_to etc_lists_url, notice: 'Etc list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_etc_list
      @etc_list = EtcList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def etc_list_params
      params.require(:etc_list).permit(:name)
    end
end

app/helpers/etc_lists_helper.rb
module EtcListsHelper
end

app/helpers/paths_helper.rb
module PathsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/etc_lists/_form.html.erb
<%= form_with(model: etc_list, local: true) do |form| %>
  <% if etc_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(etc_list.errors.count, "error") %> prohibited this etc_list from being saved:</h2>

      <ul>
      <% etc_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :etc_list_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/etc_lists/edit.html.erb
<h1>Editing Etc List</h1>

<%= render 'form', etc_list: @etc_list %>

<%= link_to 'Show', @etc_list %> |
<%= link_to 'Back', etc_lists_path %>

app/views/etc_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Etc Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @etc_lists.each do |etc_list| %>
      <tr>
        <td><%= etc_list.name %></td>
        <td><%= link_to 'Show', etc_list %></td>
        <td><%= link_to 'Edit', edit_etc_list_path(etc_list) %></td>
        <td><%= link_to 'Destroy', etc_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Etc List', new_etc_list_path %>

app/views/etc_lists/new.html.erb
<h1>New Etc List</h1>

<%= render 'form', etc_list: @etc_list %>

<%= link_to 'Back', etc_lists_path %>

app/views/etc_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @etc_list.name %>
</p>

<%= link_to 'Edit', edit_etc_list_path(@etc_list) %> |
<%= link_to 'Back', etc_lists_path %>